apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{required "A valid .Values.port_http entry required!" .Values.port_http}}
  type: ClusterIP
  selector:
    name: {{.Chart.Name}}
